version: '3.0'

services:
  app:
      container_name: app
      build:
        context: .
      env_file:
        - .env.development
      volumes:
        - .:/app
        - /app/node_modules
      ports:
        - "5000:5000"
        - "9229:9229"
      command: npm run start:dev
      depends_on:
        - postgres
      restart: always
  postgres:
    container_name: postgres
    image: postgres:15
    env_file:
      - .env.development
    environment:
      PG_DATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always


volumes:
  pgdata:
